---
- name: Get disk size from VM template and create VM
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vm_provision_vars.yml
  tasks:
    - name: create VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        template: "{{ vm_template }}"
        name: "{{ vm_name }}"
        state: "{{ vm_state }}"
        cluster: "{{ vcenter_cluster }}"
        folder: "{{ vcenter_destination_folder }}"
        hardware:
          memory_mb: "{{ memory_mb }}"
          num_cpus: "{{ num_cpus }}"
        networks:
        - name: "{{ network_name }}"
          start_connected: yes
          dvswitch_name: "{{ dswitch }}"
          ip: "{{ ip }}"
          netmask: "{{ netmask }}"
          gateway: "{{ gateway }}"
          type: static
        disk: "{{ vm_disks }}"
        customization:
          password: win_admin_password
    - name: change network
      vmware_guest_network:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        name: "{{ vm_name }}"
        gather_network_info: false
        vlan_id: "{{ vlan_id }}"
        label: "Network adapter 1"
        connected: true
        state: present
